---
 - name: build configs
   hosts: ciscohosts 
   connection: local
   gather_facts: no
   vars:
    un: "cisco"
    pwd: "cisco"
    os: "ios"
   tasks:
    - name: build configs
      template:
       src=templates/core.j2
       dest=configs/{{ inventory_hostname }}.conf
    - name: push configs
      napalm_install_config:
        hostname={{ inventory_hostname }}
        username={{ un }}
        password={{ pwd }}
        dev_os={{ os }}
        config_file=configs/{{ inventory_hostname }}.conf
        commit_changes=1
        replace_config=0
